version: "3.4"

services:
    api:
        environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        container_name: api
        build:
          context: Backend
          dockerfile: Dockerfile
        ports:
          - "7053:80"
        depends_on:
          - db
        networks: 
          - meowNetwork

    db:
        container_name: db
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
        networks: 
          - meowNetwork
    
networks:
  meowNetwork:
