name : Demo Workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  print:
    runs-on: windows-latest
    steps: 
      - name: Build
        run: cd ./AuthService/ && dotnet build
      - name: Publish
        run: dotnet publish