name : Demo Workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  print:
    runs-on: windows-latest
    steps: 
      - name: Print 1
        run: echo "1"
      - name: Print 2
        run: echo "2"