name : Demo Workflow
on: push
jobs:
  backend-ubuntu:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend/AuthService
    steps: 
      - uses: actions/checkout@v3
      - name: Check dotnet version
        run: dotnet --version
      - name: Build
        run:  dotnet build
      - name: Publish
        run:  dotnet publish
  backend-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./Backend/AuthService
    steps: 
      - uses: actions/checkout@v3
      - name: Check dotnet version
        run:  dotnet --version
      - name: Build
        run:  dotnet build
      - name: Publish
        run: dotnet publish