name : Demo Workflow
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: push
jobs:
  print:
    runs-on: windows-latest
    steps: 
      - name: Build
        run: dir&& cd .. && dir && cd ..&& dir
      - name: Publish
        run: dotnet publish